### ISSUE TITLE
ReferenceError: __hola_xyzzy__ is not defined

### ISSUE THREAD

**Issue by Nayjest** [hola/challenge_haggling#5] opened 2018-06-21 11:57 UTC
Running example code:
node haggle.js --id me@example.com:1234abcd example.js wss://hola.org/challenges/haggling/arena/standard

on Win10 x64, node v10.4.1

`
Connecting to wss://hola.org/challenges/haggling/arena/standard (ID hash a9372b48ec687591388812d244f2f9fd)...

Connected to remote server, waiting for partner...

There are a book, a hat and a ball. You have 5 rounds to reach an agreement.

Alice (remote): I want everything; you get nothing.

Bob (script): ReferenceError: `__hola_xyzzy__` is not defined
`

Sometimes works as expected, sometimes get this error.

**Comment by feldgendler** [comment] 2018-06-21 12:03
I cannot reproduce this. Have you downloaded all the necessary modules according to `package.json` with `npm install`?

**Comment by Nayjest** [comment] 2018-06-21 12:31
@feldgendler yes, installed. It appears only in some runs, 50/50. 
In cases when it works ok, output starts with:
"Alice (script): 5 rounds left"
In cases when I have this error, game starts with:
"
Alice (remote): I want everything; you get nothing.
Bob (script): ReferenceError: __hola_xyzzy__ is not defined
"

**Comment by Nayjest** [comment] 2018-06-21 12:34
В общем, валится всегда, когда первый ход приходится на оппонента.

**Comment by feldgendler** [comment] 2018-06-21 12:36
Is it with the original `example.js` included in the repository? And is it with the latest version (current `master`)?

**Comment by Nayjest** [comment] 2018-06-21 12:38
Yes, 
1)  original example.js
2)  latest version downloaded as .zip, from master branch today few hours ago.
* Add versioning to your package please

**Comment by Nayjest** [comment] 2018-06-21 13:03
It appears in loader.js Line 97

**Comment by feldgendler** [comment] 2018-06-21 13:15
I know, but it gets assigned in loader.js line 85, and works for me 100% of the time.

**Comment by feldgendler** [comment] 2018-06-21 13:46
We don't have version numbers here because we aren't publishing this project as an NPM module. I don't recommend downloading the zip snapshots because it can indeed be hard to keep track of how fresh it is. Please use git to keep a copy of our repository up-to-date.

Please try again with the most recent `master`.

**Comment by Nayjest** [comment] 2018-06-21 14:12
I don't know details how it works, but what I see:
It never goes into "init" if first turn is not my.
I added following code:
`process.send({type: 'abort', data:"it works"});`
after
 `case 'init': try {`


Now if first turn is my, process is terminated by my message as expected:
`Alice (script): it works` 


But when opponent makes first turn. I get:
`Alice (remote): I want everything; you get nothing.`
`Bob (script): ReferenceError: __hola_xyzzy__ is not defined`
`Disconnected from remote server`

**Comment by Nayjest** [comment] 2018-06-21 14:13
* that was on old code, I will try last master now

**Comment by Nayjest** [comment] 2018-06-21 14:19
I tried to use most recent master, same issue:
![Fresh Screen](https://i.gyazo.com/b5f2d065066e540df5b490819ee51708.png)

**Comment by feldgendler** [comment] 2018-06-21 14:21
This might be a Windows-specific timing issue. Can you check if this patch helps?

```diff
diff --git a/src/loader.js b/src/loader.js
index 82407ee..4461ce5 100644
--- a/src/loader.js
+++ b/src/loader.js
@@ -10,12 +10,6 @@ class AI extends events.EventEmitter {
         this.timer = undefined;
         this.timeout = timeout;
         this.worker = cluster.fork({script});
-        this.worker.addListener('online', ()=>{
-            this.worker.send({type: 'init',
-                data: [me, counts, values, max_rounds]});
-            if (me==0)
-                this.offer();
-        });
         this.worker.addListener('message', ({type, data})=>{
             switch (type)
             {
@@ -37,6 +31,10 @@ class AI extends events.EventEmitter {
                 return this.emit('abort', data);
             }
         });
+        this.worker.send({type: 'init',
+            data: [me, counts, values, max_rounds]});
+        if (me==0)
+            this.offer();
     }
     label(){ return 'script'; }
     offer(o){
```

**Comment by Nayjest** [comment] 2018-06-21 14:29
Yep, your patch fixed it.
Thanx!

**Comment by feldgendler** [comment] 2018-06-21 14:30
I have committed the fix. Thanks for reporting the bug!

**Closed** 2018-06-21 14:30 UTC
